# Importation des données

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_clients = pd.read_excel("C:/Users/testa/Documents/Zalya_Stage/DATA/REEL DATA.xlsx", sheet_name = "Répertoire clients")

In [3]:
df_clients.head()

,Clients,E-mail,Téléphone,Adresse
0,Moussa YARA,moussayara2004@gmail.com,05 640 27 27,Grand marché
1,Centre médical la Colombe,NaN,NaN,Case du parti Mvoumvou
2,Desmon Esperith KIBINDA,kibindaesperith@gmail.com,05 598 24 32,Makayabou Ngofo
3,WILLIS TOWERS WATSON,thierry-robert.nsikou@wtwco.com,06 663 85 25,"Avenue Charles de Gaulles, Centre-Ville"
4,Gracia IKOUADJA,gracia.ikouadja@wtwco.com,05 207 49 45,"Avenue Charles de Gaulles, Centre-Ville"

In [4]:
df_clients.columns

Index(['Clients', 'E-mail', ' Téléphone', 'Adresse '], dtype='str')

In [5]:
df_clients.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Clients     7 non-null      str
 1   E-mail      4 non-null      str
 2    Téléphone  5 non-null      str
 3   Adresse     7 non-null      str
dtypes: str(4)
memory usage: 356.0 bytes

***Vérification des valeurs valeurs manquantes***

In [6]:
print(df_clients.isnull().sum())

Clients       0
E-mail        3
 Téléphone    2
Adresse       0
dtype: int64

***Abscences de 3 E_mail et 2 numéros de téléphone acceptable***

In [7]:
print(df_clients.duplicated().sum())

0

***Pas de doublants***

### Uniformisation du texte

In [8]:
df_clients["Clients"] = (
    df_clients["Clients"]
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
    .str.replace(r"[^a-zA-Z0-9\s]", "", regex=True)
)

In [9]:
df_clients.rename(columns={
    " Téléphone": "Telephone",
    "E-mail": "E_mail"
}, inplace=True)

In [10]:
df_clients["E_mail"]= df_clients["E_mail"].fillna("Vide")
df_clients["Telephone"]= df_clients["Telephone"].fillna("Vide")

In [11]:
df_clients.head()

,Clients,E_mail,Telephone,Adresse
0,moussa yara,moussayara2004@gmail.com,05 640 27 27,Grand marché
1,centre mdical la colombe,Vide,Vide,Case du parti Mvoumvou
2,desmon esperith kibinda,kibindaesperith@gmail.com,05 598 24 32,Makayabou Ngofo
3,willis towers watson,thierry-robert.nsikou@wtwco.com,06 663 85 25,"Avenue Charles de Gaulles, Centre-Ville"
4,gracia ikouadja,gracia.ikouadja@wtwco.com,05 207 49 45,"Avenue Charles de Gaulles, Centre-Ville"

### Vérification de clients sans nom

In [12]:
df_clients[ df_clients["Clients"].isnull()]

Empty DataFrame
Columns: [Clients, E_mail, Telephone, Adresse ]
Index: []

In [13]:
# Création d'une clé pour les liens avec les autres entités
df_clients["client_id"] = range(  1,len(df_clients) + 1)

In [14]:
df_clients

,Clients,E_mail,Telephone,Adresse,client_id
0,moussa yara,moussayara2004@gmail.com,05 640 27 27,Grand marché,1
1,centre mdical la colombe,Vide,Vide,Case du parti Mvoumvou,2
2,desmon esperith kibinda,kibindaesperith@gmail.com,05 598 24 32,Makayabou Ngofo,3
3,willis towers watson,thierry-robert.nsikou@wtwco.com,06 663 85 25,"Avenue Charles de Gaulles, Centre-Ville",4
4,gracia ikouadja,gracia.ikouadja@wtwco.com,05 207 49 45,"Avenue Charles de Gaulles, Centre-Ville",5
5,kwiza beach,Vide,06 801 70 49,"Zone cotière, Centre-Ville",6
6,prince koubaka,Vide,Vide,Tchibamba,7

In [16]:
df_clients.rename(columns={
    "Clients": "client",
    "E_mail": "email",
    "Telephone": "telephone",
    "Adresse ": "adresse"
}, inplace=True)

In [19]:
colonnes_texte = [
    "client",
    "adresse"
]
for col in colonnes_texte:
    if col in df_clients.columns:
        df_clients[col] = (
            df_clients[col]
            .astype(str)
            .str.strip()
            .str.lower()
        )

In [20]:
df_clients

,client,email,telephone,adresse,client_id
0,moussa yara,moussayara2004@gmail.com,05 640 27 27,grand marché,1
1,centre mdical la colombe,Vide,Vide,case du parti mvoumvou,2
2,desmon esperith kibinda,kibindaesperith@gmail.com,05 598 24 32,makayabou ngofo,3
3,willis towers watson,thierry-robert.nsikou@wtwco.com,06 663 85 25,"avenue charles de gaulles, centre-ville",4
4,gracia ikouadja,gracia.ikouadja@wtwco.com,05 207 49 45,"avenue charles de gaulles, centre-ville",5
5,kwiza beach,Vide,06 801 70 49,"zone cotière, centre-ville",6
6,prince koubaka,Vide,Vide,tchibamba,7

In [21]:
df_clients.to_csv("clients_clean.csv", index= False)