In [1]:
import pandas as pd

# Importation des données opérationnelles

In [4]:
xlsx = pd.ExcelFile("C:/Users/testa/Documents/Zalya_Stage/DATA/REEL DATA.xlsx")
print(xlsx.sheet_names)

['Ventes', 'Services-Produits', 'Répertoire clients', 'Dévis et bon de commande', 'operations ']

In [6]:
df_operations = pd.read_excel(
 "C:/Users/testa/Documents/Zalya_Stage/DATA/REEL DATA.xlsx",
    sheet_name="operations "
)

In [7]:
df_operations.head()

,Service,Date de Facture,Description,Bénéficiaire,Montant HT,TVA,CA,Montant TTC
0,Fourniture bureau,2026-01-03,Achat perforateur,HS SOLUTIONS,5000.00,NaN,NaN,5000.00000
1,Fourniture bureau,2026-01-06,Achat Amoire réception,AGS ELECTRO,75000.00,NaN,NaN,75000.00000
2,Fourniture bureau,2026-01-06,Achat chaise,AVENIR PLUS,32000.00,NaN,NaN,32000.00000
3,Fourniture bureau,2026-01-06,Achat tirroir,ETS YC,30000.00,NaN,NaN,30000.00000
4,Internet,2026-01-06,Abonnement mois de janvier,congo telecom,12615.64,2270.8152,113.54076,14999.99596

In [8]:
# Standardisation des colonnes
df_operations.columns = (
    df_operations.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("/", "_")
)

In [10]:
# Rénnomation des colonnes
df_operations.rename(columns={
    "date_de_facture": "date_facture",
    "bénéficiaire": "beneficiaire",
}, inplace=True)

In [11]:
# Supprésion de la derniere ligne total 
df_operations = df_operations[
    df_operations["service"].notna()
]

In [13]:
df_operations

,service,date_facture,description,beneficiaire,montant_ht,tva,ca,montant_ttc
0,Fourniture bureau,2026-01-03,Achat perforateur,HS SOLUTIONS,5000.00,NaN,NaN,5000.00000
1,Fourniture bureau,2026-01-06,Achat Amoire réception,AGS ELECTRO,75000.00,NaN,NaN,75000.00000
2,Fourniture bureau,2026-01-06,Achat chaise,AVENIR PLUS,32000.00,NaN,NaN,32000.00000
3,Fourniture bureau,2026-01-06,Achat tirroir,ETS YC,30000.00,NaN,NaN,30000.00000
4,Internet,2026-01-06,Abonnement mois de janvier,congo telecom,12615.64,2270.8152,113.54076,14999.99596
...,...,...,...,...,...,...,...,...
68,Prestataire,2026-03-13,Frais de prestation février,GOMA Tecia,40000.00,NaN,NaN,40000.00000
69,Transport,2026-03-17,Frais de tranport pour UTPPE,jessy bounda,2000.00,NaN,NaN,2000.00000
70,Travaux,2026-03-20,Frais de maintenance installation logiciels,Désir KOUSSAFOULA,90000.00,NaN,NaN,90000.00000
71,Travaux,2026-03-20,Frais de tranport pour l'agent E2C,E2C,5000.00,NaN,NaN,5000.00000
72,Fourniture bureau,2026-03-27,Achat bobonnes d'eau,GOMA Tecia,6000.00,NaN,NaN,6000.00000

## Nettoyage des montants

In [14]:
# colonnes financière
colonnes_montants = [
    "montant_ht",
    "tva",
    "ca",
    "montant_ttc"
]

In [15]:
# nettoyage
for col in colonnes_montants:
    df_operations[col] = (
        df_operations[col]
        .astype(str)
        .str.replace("\xa0", "", regex=False)
        .str.replace(" ", "", regex=False)
        .str.replace(",", ".", regex=False)
    )
    df_operations[col] = pd.to_numeric(
        df_operations[col],
        errors="coerce"
    )

## Conversion  des dates

In [17]:
df_operations["date_facture"] = pd.to_datetime(
    df_operations["date_facture"],
    dayfirst=True,
    errors="coerce"
)

In [18]:
df_operations["annee"] = (
    df_operations["date_facture"]
    .dt.year
)
df_operations["mois"] = (
    df_operations["date_facture"]
    .dt.month
)
df_operations["trimestre"] = (
    df_operations["date_facture"]
    .dt.quarter
)

## Uniformisation du texe

In [49]:
colonnes_textes = [
    "service",
    "description",
    "beneficiaire"
]

In [50]:
# uniformisation
for col in colonnes_textes:
    df_operations[col] = (
        df_operations[col]
        .astype(str)
        .str.strip()
        .str.lower()
    )

In [51]:
df_operations

,service,date_facture,description,beneficiaire,montant_ht,tva,ca,montant_ttc,annee,mois,trimestre,categorie_depense,operation_id
0,fourniture bureau,2026-01-03,achat perforateur,hs solutions,5000.00,NaN,NaN,5000.00000,2026,1,1,administratif,1
1,fourniture bureau,2026-01-06,achat amoire réception,ags electro,75000.00,NaN,NaN,75000.00000,2026,1,1,administratif,2
2,fourniture bureau,2026-01-06,achat chaise,avenir plus,32000.00,NaN,NaN,32000.00000,2026,1,1,administratif,3
3,fourniture bureau,2026-01-06,achat tirroir,ets yc,30000.00,NaN,NaN,30000.00000,2026,1,1,administratif,4
4,internet,2026-01-06,abonnement mois de janvier,congo telecom,12615.64,2270.8152,113.54076,14999.99596,2026,1,1,internet,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,prestataire,2026-03-13,frais de prestation février,goma tecia,40000.00,NaN,NaN,40000.00000,2026,3,1,prestations,69
69,transport,2026-03-17,frais de tranport pour utppe,jessy bounda,2000.00,NaN,NaN,2000.00000,2026,3,1,divers,70
70,travaux,2026-03-20,frais de maintenance installation logiciels,désir koussafoula,90000.00,NaN,NaN,90000.00000,2026,3,1,maintenance,71
71,travaux,2026-03-20,frais de tranport pour l'agent e2c,e2c,5000.00,NaN,NaN,5000.00000,2026,3,1,maintenance,72
72,fourniture bureau,2026-03-27,achat bobonnes d'eau,goma tecia,6000.00,NaN,NaN,6000.00000,2026,3,1,administratif,73

## Création d'une catégorie analytique financière

In [52]:
categories_depenses = {

    "fourniture bureau":
    "administratif",

    "autres achats":
    "divers",

    "travaux":
    "maintenance",

    "travaux maintenance":
    "maintenance",

    "prestataire":
    "prestations",

    "transport":
    "divers",

    "internet":
    "internet",

    "loyer":
    "logement",

    "communication":
    "administratif",

    "charges personnel":
    "divers",

    "electricité":
    "electricite"

}

In [53]:
df_operations["categorie_depense"] = (
    df_operations["service"]
    .map(categories_depenses)
)

In [54]:
df_operations

,service,date_facture,description,beneficiaire,montant_ht,tva,ca,montant_ttc,annee,mois,trimestre,categorie_depense,operation_id
0,fourniture bureau,2026-01-03,achat perforateur,hs solutions,5000.00,NaN,NaN,5000.00000,2026,1,1,administratif,1
1,fourniture bureau,2026-01-06,achat amoire réception,ags electro,75000.00,NaN,NaN,75000.00000,2026,1,1,administratif,2
2,fourniture bureau,2026-01-06,achat chaise,avenir plus,32000.00,NaN,NaN,32000.00000,2026,1,1,administratif,3
3,fourniture bureau,2026-01-06,achat tirroir,ets yc,30000.00,NaN,NaN,30000.00000,2026,1,1,administratif,4
4,internet,2026-01-06,abonnement mois de janvier,congo telecom,12615.64,2270.8152,113.54076,14999.99596,2026,1,1,internet,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,prestataire,2026-03-13,frais de prestation février,goma tecia,40000.00,NaN,NaN,40000.00000,2026,3,1,prestations,69
69,transport,2026-03-17,frais de tranport pour utppe,jessy bounda,2000.00,NaN,NaN,2000.00000,2026,3,1,divers,70
70,travaux,2026-03-20,frais de maintenance installation logiciels,désir koussafoula,90000.00,NaN,NaN,90000.00000,2026,3,1,maintenance,71
71,travaux,2026-03-20,frais de tranport pour l'agent e2c,e2c,5000.00,NaN,NaN,5000.00000,2026,3,1,maintenance,72
72,fourniture bureau,2026-03-27,achat bobonnes d'eau,goma tecia,6000.00,NaN,NaN,6000.00000,2026,3,1,administratif,73

In [32]:
# montant_nul
df_operations[
    df_operations["montant_ttc"] <= 0
]

Empty DataFrame
Columns: [service, date_facture, description, beneficiaire, montant_ht, tva, ca, montant_ttc, annee, mois, trimestre, categorie_depense]
Index: []

In [33]:
# fournisseur manquant
df_operations[
    df_operations["beneficiaire"].isnull()
]

Empty DataFrame
Columns: [service, date_facture, description, beneficiaire, montant_ht, tva, ca, montant_ttc, annee, mois, trimestre, categorie_depense]
Index: []

In [34]:
# montant négatif
df_operations[
    df_operations["montant_ttc"] < 0
]

Empty DataFrame
Columns: [service, date_facture, description, beneficiaire, montant_ht, tva, ca, montant_ttc, annee, mois, trimestre, categorie_depense]
Index: []

In [35]:
# ID operation
df_operations["operation_id"] = range(
    1,
    len(df_operations) + 1
)

In [56]:
df_operations.to_csv("operations.csv", index= False)