In [1]:
import pandas as pd

# Importation des données de devis et commandes

In [2]:
df_devis_commandes = pd.read_excel("C:/Users/testa/Documents/Zalya_Stage/DATA/REEL DATA.xlsx", sheet_name = "Dévis et bon de commande")

In [3]:
df_devis_commandes.head()

,Référence commande,Date de création,Client,Vendeur,Activités,Total,Statut
0,S00027,2026-03-27 14:11:04,Gracia Ikouadja,Prince NGOMA,NaN,19619,Commande client
1,S00028,2026-03-27 17:01:05,Paola MAPAGA,Prince NGOMA,NaN,20214,Commande client
2,S00022,2026-03-12 14:33:23,"Particulier, Desmon Esperith KIBINDA",Prince NGOMA,NaN,314847,Commande client
3,S00026,2026-03-26 15:07:33,ZEUS Lounge Bar,Prince NGOMA,NaN,104038,Devis
4,S00025,2026-03-13 10:41:07,ZEUS Lounge Bar,Prince NGOMA,NaN,951200,Devis

In [4]:
df_devis_commandes.columns = (
    df_devis_commandes.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("/", "_")
)

In [5]:
print(df_devis_commandes.columns)

Index(['référence_commande', 'date_de_création', 'client', 'vendeur',
       'activités', 'total', 'statut'],
      dtype='str')

In [6]:
df_devis_commandes.rename(columns={
    "référence_commande": "reference_commande",
    "date_de_création": "date_creation",
    "total": "montant",
    "activités": "activite"
}, inplace=True)

In [7]:
print(df_devis_commandes.columns)

Index(['reference_commande', 'date_creation', 'client', 'vendeur', 'activite',
       'montant', 'statut'],
      dtype='str')

In [8]:
# Nettoyage des montants
df_devis_commandes["montant"] = (
    df_devis_commandes["montant"]
    .astype(str)
    .str.replace("\xa0", "", regex=False)
    .str.replace(" ", "", regex=False)
    .str.replace(",", ".", regex=False)
)

In [9]:
df_devis_commandes["montant"] = pd.to_numeric(
    df_devis_commandes["montant"],
    errors="coerce"
)

In [10]:
df_devis_commandes.head()

,reference_commande,date_creation,client,vendeur,activite,montant,statut
0,S00027,2026-03-27 14:11:04,Gracia Ikouadja,Prince NGOMA,NaN,19619,Commande client
1,S00028,2026-03-27 17:01:05,Paola MAPAGA,Prince NGOMA,NaN,20214,Commande client
2,S00022,2026-03-12 14:33:23,"Particulier, Desmon Esperith KIBINDA",Prince NGOMA,NaN,314847,Commande client
3,S00026,2026-03-26 15:07:33,ZEUS Lounge Bar,Prince NGOMA,NaN,104038,Devis
4,S00025,2026-03-13 10:41:07,ZEUS Lounge Bar,Prince NGOMA,NaN,951200,Devis

In [11]:
# Conversion des dates
df_devis_commandes["date_creation"] = pd.to_datetime(
    df_devis_commandes["date_creation"],
    dayfirst=True,
    errors="coerce"
)

In [12]:
df_devis_commandes["annee"] = (
    df_devis_commandes["date_creation"]
    .dt.year
)
df_devis_commandes["mois"] = (
    df_devis_commandes["date_creation"]
    .dt.month
)
df_devis_commandes["trimestre"] = (
    df_devis_commandes["date_creation"]
    .dt.quarter
)

### Uniformisation du texte

In [13]:
df_devis_commandes["client"] = (
    df_devis_commandes["client"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [14]:
df_devis_commandes["vendeur"] = (
    df_devis_commandes["vendeur"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [15]:
# Statut 
df_devis_commandes["statut"] = (
    df_devis_commandes["statut"]
    .astype(str)
    .str.strip()
    .str.lower()
)

In [16]:
df_devis_commandes.head()

,reference_commande,date_creation,client,vendeur,activite,montant,statut,annee,mois,trimestre
0,S00027,2026-03-27 14:11:04,GRACIA IKOUADJA,PRINCE NGOMA,NaN,19619,commande client,2026,3,1
1,S00028,2026-03-27 17:01:05,PAOLA MAPAGA,PRINCE NGOMA,NaN,20214,commande client,2026,3,1
2,S00022,2026-03-12 14:33:23,"PARTICULIER, DESMON ESPERITH KIBINDA",PRINCE NGOMA,NaN,314847,commande client,2026,3,1
3,S00026,2026-03-26 15:07:33,ZEUS LOUNGE BAR,PRINCE NGOMA,NaN,104038,devis,2026,3,1
4,S00025,2026-03-13 10:41:07,ZEUS LOUNGE BAR,PRINCE NGOMA,NaN,951200,devis,2026,3,1

In [17]:
# variable analytique
df_devis_commandes["type_transaction"] = (
    df_devis_commandes["statut"]
)

In [18]:
# Indicateur de convertion 
df_devis_commandes["conversion"] = (
    df_devis_commandes["statut"]
    == "commande client"
)

In [19]:
df_devis_commandes.head()

,reference_commande,date_creation,client,vendeur,activite,montant,statut,annee,mois,trimestre,type_transaction,conversion
0,S00027,2026-03-27 14:11:04,GRACIA IKOUADJA,PRINCE NGOMA,NaN,19619,commande client,2026,3,1,commande client,True
1,S00028,2026-03-27 17:01:05,PAOLA MAPAGA,PRINCE NGOMA,NaN,20214,commande client,2026,3,1,commande client,True
2,S00022,2026-03-12 14:33:23,"PARTICULIER, DESMON ESPERITH KIBINDA",PRINCE NGOMA,NaN,314847,commande client,2026,3,1,commande client,True
3,S00026,2026-03-26 15:07:33,ZEUS LOUNGE BAR,PRINCE NGOMA,NaN,104038,devis,2026,3,1,devis,False
4,S00025,2026-03-13 10:41:07,ZEUS LOUNGE BAR,PRINCE NGOMA,NaN,951200,devis,2026,3,1,devis,False

In [20]:
#Suppression de la colonne activite
# df_devis_commandes= df_devis_commandes.drop("activite", axis= 1)

In [21]:
# référence dupliquée
df_devis_commandes[
    df_devis_commandes["reference_commande"]
    .duplicated()
]

Empty DataFrame
Columns: [reference_commande, date_creation, client, vendeur, activite, montant, statut, annee, mois, trimestre, type_transaction, conversion]
Index: []

In [22]:
# ID
df_devis_commandes["transaction_id"] = range(
    1,
    len(df_devis_commandes) + 1
)

In [23]:
df_devis_commandes.head()

,reference_commande,date_creation,client,vendeur,activite,montant,statut,annee,mois,trimestre,type_transaction,conversion,transaction_id
0,S00027,2026-03-27 14:11:04,GRACIA IKOUADJA,PRINCE NGOMA,NaN,19619,commande client,2026,3,1,commande client,True,1
1,S00028,2026-03-27 17:01:05,PAOLA MAPAGA,PRINCE NGOMA,NaN,20214,commande client,2026,3,1,commande client,True,2
2,S00022,2026-03-12 14:33:23,"PARTICULIER, DESMON ESPERITH KIBINDA",PRINCE NGOMA,NaN,314847,commande client,2026,3,1,commande client,True,3
3,S00026,2026-03-26 15:07:33,ZEUS LOUNGE BAR,PRINCE NGOMA,NaN,104038,devis,2026,3,1,devis,False,4
4,S00025,2026-03-13 10:41:07,ZEUS LOUNGE BAR,PRINCE NGOMA,NaN,951200,devis,2026,3,1,devis,False,5

In [24]:
df_devis_commandes["type_transaction"].value_counts()

type_transaction
commande client    16
devis              12
Name: count, dtype: int64

In [25]:
df_devis_commandes["mois"].value_counts()

mois
3     10
2     10
1      3
11     3
12     1
10     1
Name: count, dtype: int64

In [27]:
colonnes_texte = [
    "client",
    "vendeur"
]
for col in colonnes_texte:
    if col in df_devis_commandes.columns:
        df_devis_commandes[col] = (
            df_devis_commandes[col]
            .astype(str)
            .str.strip()
            .str.lower()
        )

In [28]:
df_devis_commandes.head()

,reference_commande,date_creation,client,vendeur,activite,montant,statut,annee,mois,trimestre,type_transaction,conversion,transaction_id
0,S00027,2026-03-27 14:11:04,gracia ikouadja,prince ngoma,NaN,19619,commande client,2026,3,1,commande client,True,1
1,S00028,2026-03-27 17:01:05,paola mapaga,prince ngoma,NaN,20214,commande client,2026,3,1,commande client,True,2
2,S00022,2026-03-12 14:33:23,"particulier, desmon esperith kibinda",prince ngoma,NaN,314847,commande client,2026,3,1,commande client,True,3
3,S00026,2026-03-26 15:07:33,zeus lounge bar,prince ngoma,NaN,104038,devis,2026,3,1,devis,False,4
4,S00025,2026-03-13 10:41:07,zeus lounge bar,prince ngoma,NaN,951200,devis,2026,3,1,devis,False,5

In [29]:
df_devis_commandes.to_csv("devis_clean.csv", index= False)