In [1]:
import pandas as pd
# Chargement des fichiers
df_ventes = pd.read_csv("C:/Users/testa/Documents/Zalya_Stage/DATA/Nettoyées/ventes_clean.csv")
df_operations = pd.read_csv("C:/Users/testa/Documents/Zalya_Stage/DATA/Nettoyées/operations_clean.csv")
df_clients = pd.read_csv("C:/Users/testa/Documents/Zalya_Stage/DATA/Nettoyées/clients_clean.csv")
df_services = pd.read_csv("C:/Users/testa/Documents/Zalya_Stage/DATA/Nettoyées/services_clean.csv")
df_devis = pd.read_csv("C:/Users/testa/Documents/Zalya_Stage/DATA/Nettoyées/devis_clean.csv")

In [2]:
df_ventes.head()

,Service,Date_facture,Date_echeance,Num_facture,Clients,Montant_HT,TVA,CA,Montant_TTC,Date_paiement,Mode_paiement,Statut,annee,mois,jour,vente_id
0,communication,2026-01-16,2026-01-16,INV/2026/00008,moussa yara,42053,7569.54,378.477,50001.017,2026-01-16,Espèces,Payé,2026.0,1.0,16.0,1
1,communication,2026-02-05,2026-02-05,Vide,moussa yara,42053,7569.54,378.477,50001.017,2026-02-05,Espèces,Payé,2026.0,2.0,5.0,2
2,communication,2026-03-25,2026-03-25,INV/2026/00015,moussa yara,42053,7569.54,378.477,50001.017,2026-03-25,Espèces,Payé,2026.0,3.0,25.0,3
3,importation,2026-01-09,2026-01-09,INV/2026/00005,desmon esperith kibinda,315000,56700.00,2835.000,374535.000,2026-01-09,Espèces,Payé,2026.0,1.0,9.0,4
4,importation,2026-03-12,2026-03-12,INV/2026/00014,desmon esperith kibinda,264800,47664.00,2383.200,314847.200,2026-03-12,Espèces,Payé,2026.0,3.0,12.0,5

In [3]:
df_clients.head()

,Clients,E_mail,Telephone,Adresse,client_id
0,moussa yara,moussayara2004@gmail.com,05 640 27 27,Grand marché,1
1,centre mdical la colombe,Vide,Vide,Case du parti Mvoumvou,2
2,desmon esperith kibinda,kibindaesperith@gmail.com,05 598 24 32,Makayabou Ngofo,3
3,willis towers watson,thierry-robert.nsikou@wtwco.com,06 663 85 25,"Avenue Charles de Gaulles, Centre-Ville",4
4,gracia ikouadja,gracia.ikouadja@wtwco.com,05 207 49 45,"Avenue Charles de Gaulles, Centre-Ville",5

In [4]:
df_services.head()

,nom_service,service_id,categorie,actif,prix_reference,cout_estime,marge_estimee
0,conception web,1,digital,True,NaN,NaN,NaN
1,développement plateformes ou logiciels,2,digital,True,NaN,NaN,NaN
2,communication digitale,3,marketing,True,NaN,NaN,NaN
3,imprimerie,4,print_media,True,NaN,NaN,NaN
4,imporation,5,logistique,True,NaN,NaN,NaN

In [5]:
df_devis.head()

,reference_commande,date_creation,client,vendeur,montant,statut,annee,mois,trimestre,type_transaction,conversion,transaction_id
0,S00027,2026-03-27 14:11:04,GRACIA IKOUADJA,PRINCE NGOMA,19619,commande client,2026,3,1,commande client,True,1
1,S00028,2026-03-27 17:01:05,PAOLA MAPAGA,PRINCE NGOMA,20214,commande client,2026,3,1,commande client,True,2
2,S00022,2026-03-12 14:33:23,"PARTICULIER, DESMON ESPERITH KIBINDA",PRINCE NGOMA,314847,commande client,2026,3,1,commande client,True,3
3,S00026,2026-03-26 15:07:33,ZEUS LOUNGE BAR,PRINCE NGOMA,104038,devis,2026,3,1,devis,False,4
4,S00025,2026-03-13 10:41:07,ZEUS LOUNGE BAR,PRINCE NGOMA,951200,devis,2026,3,1,devis,False,5

In [6]:
df_operations.head()

,service,date_facture,description,beneficiaire,montant_ht,tva,ca,montant_ttc,annee,mois,trimestre,categorie_depense,operation_id
0,fourniture bureau,2026-01-03,achat perforateur,hs solutions,5000.00,NaN,NaN,5000.00000,2026,1,1,administratif,1
1,fourniture bureau,2026-01-06,achat amoire réception,ags electro,75000.00,NaN,NaN,75000.00000,2026,1,1,administratif,2
2,fourniture bureau,2026-01-06,achat chaise,avenir plus,32000.00,NaN,NaN,32000.00000,2026,1,1,administratif,3
3,fourniture bureau,2026-01-06,achat tirroir,ets yc,30000.00,NaN,NaN,30000.00000,2026,1,1,administratif,4
4,internet,2026-01-06,abonnement mois de janvier,congo telecom,12615.64,2270.8152,113.54076,14999.99596,2026,1,1,internet,5

In [7]:
print(df_ventes.columns)
print(df_clients.columns)
print(df_services.columns)
print(df_devis.columns)
print(df_operations.columns)

Index(['Service', 'Date_facture', 'Date_echeance', 'Num_facture', 'Clients',
       'Montant_HT', 'TVA', 'CA', 'Montant_TTC', 'Date_paiement',
       'Mode_paiement', 'Statut', 'annee', 'mois', 'jour', 'vente_id'],
      dtype='str')
Index(['Clients', 'E_mail', 'Telephone', 'Adresse ', 'client_id'], dtype='str')
Index(['nom_service', 'service_id', 'categorie', 'actif', 'prix_reference',
       'cout_estime', 'marge_estimee'],
      dtype='str')
Index(['reference_commande', 'date_creation', 'client', 'vendeur', 'montant',
       'statut', 'annee', 'mois', 'trimestre', 'type_transaction',
       'conversion', 'transaction_id'],
      dtype='str')
Index(['service', 'date_facture', 'description', 'beneficiaire', 'montant_ht',
       'tva', 'ca', 'montant_ttc', 'annee', 'mois', 'trimestre',
       'categorie_depense', 'operation_id'],
      dtype='str')

## Harmonisation globale des colonnes

In [8]:
df_ventes.rename(columns={
    "Service": "service",
    "Clients": "client",
    "Montant_HT": "montant_ht",
    "Montant_TTC": "montant_ttc",
    "TVA": "tva",
    "CA": "ca",
    "Statut": "statut"
}, inplace=True)

In [9]:
df_clients.rename(columns={
    "Clients": "client",
    "E_mail": "email",
    "Telephone": "telephone",
    "Adresse ": "adresse"
}, inplace=True)

## Uniformisation du texte

In [10]:
colonnes_texte = [
    "client",
    "service",
    "statut"
]
for col in colonnes_texte:
    if col in df_ventes.columns:
        df_ventes[col] = (
            df_ventes[col]
            .astype(str)
            .str.strip()
            .str.lower()
        )

In [11]:
colonnes_texte = [
    "client",
    "adresse"
]
for col in colonnes_texte:
    if col in df_clients.columns:
        df_clients[col] = (
            df_clients[col]
            .astype(str)
            .str.strip()
            .str.lower()
        )

In [12]:
colonnes_texte = [
    "client",
    "vendeur"
]
for col in colonnes_texte:
    if col in df_devis.columns:
        df_devis[col] = (
            df_devis[col]
            .astype(str)
            .str.strip()
            .str.lower()
        )

## Vérification des relations métiers

In [13]:
### verification
clients_ventes = set(df_ventes["client"])
clients_clients = set(df_clients["client"])

In [14]:
### clients manquants
clients_absents = (
    clients_ventes
    - clients_clients
)
print(clients_absents)

set()

In [15]:
## services-ventes
### vérification
services_ventes = set(
    df_ventes["service"]
)
services_catalogue = set(

    df_services["nom_service"]
)

### services manquants
services_absents = (
    services_ventes
    - services_catalogue
)
print(services_absents)

{'communication', 'importation'}

In [16]:
df_services["nom_service"]= df_services["nom_service"].replace({
    "communication digitale": "communication",
    "imporation": "importation",
})

In [17]:
## services-ventes
### vérification
services_ventes = set(
    df_ventes["service"]
)
services_catalogue = set(

    df_services["nom_service"]
)

### services manquants
services_absents = (
    services_ventes
    - services_catalogue
)
print(services_absents)

set()

In [18]:
### devis-clients
clients_devis = set(

    df_devis["client"]
)
clients_absents_devis = (

    clients_devis

    - clients_clients
)
print(clients_absents_devis)

{'kwiza beach pnr', 'emeraude sante assurances et reassurances congo', 'doxa consulting', 'ndt tech solutions', 'kwiza beach pnr, rovick massala', 'melki', 'sl production, mr caustodel', 'particulier, desmon esperith kibinda', 'paola mapaga', 'mr boukaka', 'zeus lounge bar', 'avenir plus, moussa yara', 'sl production', 'ets kgf', 'management organisationnel', 'desmon kibinda', 'centre médical la colombe'}

In [19]:
services_operations = set(

    df_operations["service"]
)
print(services_operations)

{'transport', 'internet', 'fourniture bureau', 'travaux maintenance', 'loyer', 'communication', 'electricité', 'autres achats', 'travaux', 'charges personnel', 'prestataire'}

**opérations ≠ catalogue de services.**

## Vérification des doublons

In [20]:
print(
    df_ventes
    .duplicated()
    .sum()
)

0

In [21]:
print(
    df_clients
    .duplicated()
    .sum()
)

0

In [22]:
print(
    df_devis
    .duplicated()
    .sum()
)

0

## Vérification des valeurs nulles

In [23]:
print(
    df_ventes
    .isnull()
    .sum()
)

service          0
Date_facture     0
Date_echeance    0
Num_facture      0
client           0
montant_ht       0
tva              0
ca               0
montant_ttc      0
Date_paiement    1
Mode_paiement    0
statut           0
annee            1
mois             1
jour             1
vente_id         0
dtype: int64

In [24]:
print(
    df_clients
    .isnull()
    .sum()
)

client       0
email        0
telephone    0
adresse      0
client_id    0
dtype: int64

# Croisements des datasets

In [49]:
df_ventes_clients = pd.merge(
    df_ventes,
    df_clients,
    on="client",
    how="left"
)

In [50]:
df_ventes_clients.head()

,service,Date_facture,Date_echeance,Num_facture,client,montant_ht,tva,ca,montant_ttc,Date_paiement,Mode_paiement,statut,annee,mois,jour,vente_id,email,telephone,adresse,client_id
0,communication,2026-01-16,2026-01-16,INV/2026/00008,moussa yara,42053,7569.54,378.477,50001.017,2026-01-16,Espèces,payé,2026.0,1.0,16.0,1,moussayara2004@gmail.com,05 640 27 27,grand marché,1
1,communication,2026-02-05,2026-02-05,Vide,moussa yara,42053,7569.54,378.477,50001.017,2026-02-05,Espèces,payé,2026.0,2.0,5.0,2,moussayara2004@gmail.com,05 640 27 27,grand marché,1
2,communication,2026-03-25,2026-03-25,INV/2026/00015,moussa yara,42053,7569.54,378.477,50001.017,2026-03-25,Espèces,payé,2026.0,3.0,25.0,3,moussayara2004@gmail.com,05 640 27 27,grand marché,1
3,importation,2026-01-09,2026-01-09,INV/2026/00005,desmon esperith kibinda,315000,56700.00,2835.000,374535.000,2026-01-09,Espèces,payé,2026.0,1.0,9.0,4,kibindaesperith@gmail.com,05 598 24 32,makayabou ngofo,3
4,importation,2026-03-12,2026-03-12,INV/2026/00014,desmon esperith kibinda,264800,47664.00,2383.200,314847.200,2026-03-12,Espèces,payé,2026.0,3.0,12.0,5,kibindaesperith@gmail.com,05 598 24 32,makayabou ngofo,3

In [53]:
col_client = df_ventes_clients.pop("client")
df_ventes_clients.insert(15, "client",col_client )

In [54]:
df_ventes_clients.head()

,service,Date_facture,Date_echeance,Num_facture,montant_ht,tva,ca,montant_ttc,Date_paiement,Mode_paiement,statut,annee,mois,jour,vente_id,client,email,telephone,adresse,client_id
0,communication,2026-01-16,2026-01-16,INV/2026/00008,42053,7569.54,378.477,50001.017,2026-01-16,Espèces,payé,2026.0,1.0,16.0,1,moussa yara,moussayara2004@gmail.com,05 640 27 27,grand marché,1
1,communication,2026-02-05,2026-02-05,Vide,42053,7569.54,378.477,50001.017,2026-02-05,Espèces,payé,2026.0,2.0,5.0,2,moussa yara,moussayara2004@gmail.com,05 640 27 27,grand marché,1
2,communication,2026-03-25,2026-03-25,INV/2026/00015,42053,7569.54,378.477,50001.017,2026-03-25,Espèces,payé,2026.0,3.0,25.0,3,moussa yara,moussayara2004@gmail.com,05 640 27 27,grand marché,1
3,importation,2026-01-09,2026-01-09,INV/2026/00005,315000,56700.00,2835.000,374535.000,2026-01-09,Espèces,payé,2026.0,1.0,9.0,4,desmon esperith kibinda,kibindaesperith@gmail.com,05 598 24 32,makayabou ngofo,3
4,importation,2026-03-12,2026-03-12,INV/2026/00014,264800,47664.00,2383.200,314847.200,2026-03-12,Espèces,payé,2026.0,3.0,12.0,5,desmon esperith kibinda,kibindaesperith@gmail.com,05 598 24 32,makayabou ngofo,3

In [35]:
df_ventes_services = pd.merge(
    df_ventes,
    df_services,
    left_on="service",
    right_on="nom_service",
    how="left"
)

In [36]:
df_ventes_services.head()

,service,Date_facture,Date_echeance,Num_facture,client,montant_ht,tva,ca,montant_ttc,Date_paiement,...,mois,jour,vente_id,nom_service,service_id,categorie,actif,prix_reference,cout_estime,marge_estimee
0,communication,2026-01-16,2026-01-16,INV/2026/00008,moussa yara,42053,7569.54,378.477,50001.017,2026-01-16,...,1.0,16.0,1,communication,3,marketing,True,NaN,NaN,NaN
1,communication,2026-02-05,2026-02-05,Vide,moussa yara,42053,7569.54,378.477,50001.017,2026-02-05,...,2.0,5.0,2,communication,3,marketing,True,NaN,NaN,NaN
2,communication,2026-03-25,2026-03-25,INV/2026/00015,moussa yara,42053,7569.54,378.477,50001.017,2026-03-25,...,3.0,25.0,3,communication,3,marketing,True,NaN,NaN,NaN
3,importation,2026-01-09,2026-01-09,INV/2026/00005,desmon esperith kibinda,315000,56700.00,2835.000,374535.000,2026-01-09,...,1.0,9.0,4,importation,5,logistique,True,NaN,NaN,NaN
4,importation,2026-03-12,2026-03-12,INV/2026/00014,desmon esperith kibinda,264800,47664.00,2383.200,314847.200,2026-03-12,...,3.0,12.0,5,importation,5,logistique,True,NaN,NaN,NaN

In [37]:
df_devis_clients = pd.merge(
    df_devis,
    df_clients,
    on="client",
    how="left"
)

In [39]:
df_devis_clients

,reference_commande,date_creation,client,vendeur,montant,statut,annee,mois,trimestre,type_transaction,conversion,transaction_id,email,telephone,adresse,client_id
0,S00027,2026-03-27 14:11:04,gracia ikouadja,prince ngoma,19619,commande client,2026,3,1,commande client,True,1,gracia.ikouadja@wtwco.com,05 207 49 45,"avenue charles de gaulles, centre-ville",5.0
1,S00028,2026-03-27 17:01:05,paola mapaga,prince ngoma,20214,commande client,2026,3,1,commande client,True,2,NaN,NaN,NaN,NaN
2,S00022,2026-03-12 14:33:23,"particulier, desmon esperith kibinda",prince ngoma,314847,commande client,2026,3,1,commande client,True,3,NaN,NaN,NaN,NaN
3,S00026,2026-03-26 15:07:33,zeus lounge bar,prince ngoma,104038,devis,2026,3,1,devis,False,4,NaN,NaN,NaN,NaN
4,S00025,2026-03-13 10:41:07,zeus lounge bar,prince ngoma,951200,devis,2026,3,1,devis,False,5,NaN,NaN,NaN,NaN
5,S00024,2026-03-13 08:44:56,melki,prince ngoma,220500,devis,2026,3,1,devis,False,6,NaN,NaN,NaN,NaN
6,S00023,2026-03-12 15:40:16,zeus lounge bar,prince ngoma,0,devis,2026,3,1,devis,False,7,NaN,NaN,NaN,NaN
7,S00021,2026-03-10 13:29:24,"sl production, mr caustodel",prince ngoma,14862500,devis,2026,3,1,devis,False,8,NaN,NaN,NaN,NaN
8,S00020,2026-03-04 14:05:32,doxa consulting,prince ngoma,238900,devis,2026,3,1,devis,False,9,NaN,NaN,NaN,NaN
9,S00019,2026-03-02 14:59:43,prince koubaka,prince ngoma,5992,commande client,2026,3,1,commande client,True,10,Vide,Vide,tchibamba,7.0
10,S00018,2026-02-27 11:06:52,"kwiza beach pnr, rovick massala",prince ngoma,1486,commande client,2026,2,1,commande client,True,11,NaN,NaN,NaN,NaN
11,S00011,2026-02-06 14:37:13,kwiza beach pnr,prince ngoma,19024,commande client,2026,2,1,commande client,True,12,NaN,NaN,NaN,NaN
12,S00017,2026-02-21 12:18:50,"kwiza beach pnr, rovick massala",prince ngoma,11058,commande client,2026,2,1,commande client,True,13,NaN,NaN,NaN,NaN
13,S00009,2026-02-02 13:13:02,gracia ikouadja,prince ngoma,28536,commande client,2026,2,1,commande client,True,14,gracia.ikouadja@wtwco.com,05 207 49 45,"avenue charles de gaulles, centre-ville",5.0
14,S00010,2026-02-05 17:48:29,"avenir plus, moussa yara",prince ngoma,50001,commande client,2026,2,1,commande client,True,15,NaN,NaN,NaN,NaN
15,S00016,2026-02-17 16:02:45,management organisationnel,prince ngoma,53505,devis,2026,2,1,devis,False,16,NaN,NaN,NaN,NaN
16,S00015,2026-02-13 20:05:12,mr boukaka,prince ngoma,15159750,devis,2026,2,1,devis,False,17,NaN,NaN,NaN,NaN
17,S00014,2026-02-11 16:56:46,sl production,prince ngoma,298350,devis,2026,2,1,devis,False,18,NaN,NaN,NaN,NaN
18,S00013,2026-02-11 16:03:14,ets kgf,prince ngoma,288901,devis,2026,2,1,devis,False,19,NaN,NaN,NaN,NaN
19,S00012,2026-02-11 15:04:32,ndt tech solutions,prince ngoma,298350,devis,2026,2,1,devis,False,20,NaN,NaN,NaN,NaN
20,S00008,2026-01-17 00:10:21,emeraude sante assurances et reassurances congo,prince ngoma,25682400,devis,2026,1,1,devis,False,21,NaN,NaN,NaN,NaN
21,S00007,2026-01-16 10:18:01,moussa yara,prince ngoma,50001,commande client,2026,1,1,commande client,True,22,moussayara2004@gmail.com,05 640 27 27,grand marché,1.0
22,S00006,2026-01-06 19:28:37,centre médical la colombe,prince ngoma,175824,commande client,2026,1,1,commande client,True,23,NaN,NaN,NaN,NaN
23,S00005,2025-12-02 19:33:23,desmon kibinda,prince ngoma,374535,commande client,2025,12,4,commande client,True,24,NaN,NaN,NaN,NaN
24,S00004,2025-11-21 21:25:22,willis towers watson,prince ngoma,190240,commande client,2025,11,4,commande client,True,25,thierry-robert.nsikou@wtwco.com,06 663 85 25,"avenue charles de gaulles, centre-ville",4.0
25,S00003,2025-11-03 15:40:11,willis towers watson,prince ngoma,35373,commande client,2025,11,4,commande client,True,26,thierry-robert.nsikou@wtwco.com,06 663 85 25,"avenue charles de gaulles, centre-ville",4.0
26,S00002,2025-11-03 15:32:04,willis towers watson,prince ngoma,29725,commande client,2025,11,4,commande client,True,27,thierry-robert.nsikou@wtwco.com,06 663 85 25,"avenue charles de gaulles, centre-ville",4.0
27,S00001,2025-10-19 00:37:54,willis towers watson,prince ngoma,29725,commande client,2025,10,4,commande client,True,28,thierry-robert.nsikou@wtwco.com,06 663 85 25,"avenue charles de gaulles, centre-ville",4.0

In [42]:
colonne_client = df_devis_clients.pop("client")
df_devis_clients.insert(11, "client",colonne_client )

In [43]:
df_devis_clients.head()

,reference_commande,date_creation,vendeur,montant,statut,annee,mois,trimestre,type_transaction,conversion,transaction_id,client,email,telephone,adresse,client_id
0,S00027,2026-03-27 14:11:04,prince ngoma,19619,commande client,2026,3,1,commande client,True,1,gracia ikouadja,gracia.ikouadja@wtwco.com,05 207 49 45,"avenue charles de gaulles, centre-ville",5.0
1,S00028,2026-03-27 17:01:05,prince ngoma,20214,commande client,2026,3,1,commande client,True,2,paola mapaga,NaN,NaN,NaN,NaN
2,S00022,2026-03-12 14:33:23,prince ngoma,314847,commande client,2026,3,1,commande client,True,3,"particulier, desmon esperith kibinda",NaN,NaN,NaN,NaN
3,S00026,2026-03-26 15:07:33,prince ngoma,104038,devis,2026,3,1,devis,False,4,zeus lounge bar,NaN,NaN,NaN,NaN
4,S00025,2026-03-13 10:41:07,prince ngoma,951200,devis,2026,3,1,devis,False,5,zeus lounge bar,NaN,NaN,NaN,NaN

## Analyses croisées

In [64]:
# Top clients
top_clients = (
    df_ventes_clients
    .groupby("client")["montant_ttc"]
    .sum()
    .sort_values(ascending=False)
)
print(top_clients)

client
desmon esperith kibinda     689382.200
willis towers watson        285062.750
centre mdical la colombe    175823.375
moussa yara                 150003.051
kwiza beach                  31567.950
gracia ikouadja              28536.000
prince koubaka                5992.560
Name: montant_ttc, dtype: float64

In [65]:
# Top services
top_services = (
    df_ventes_services
    .groupby("service")["montant_ttc"]
    .sum()
    .sort_values(ascending=False)
)
print(top_services)

service
importation      689382.200
imprimerie       526982.635
communication    150003.051
Name: montant_ttc, dtype: float64

***Client le plus rentable : desmon esperith kibinda***

In [60]:
# Evolution mensuelle
evolution_mensuelle = (
    df_ventes
    .groupby("mois")["montant_ttc"]
    .sum()
)
print(evolution_mensuelle)

mois
1.0    600359.392
2.0    359794.967
3.0    370840.777
Name: montant_ttc, dtype: float64

In [61]:
# Comparaison revenu VS dépense 
revenus = (
    df_ventes
    .groupby("mois")["montant_ttc"]
    .sum()
)
depenses = (
    df_operations
    .groupby("mois")["montant_ttc"]
    .sum()
)

In [62]:
# fusion
comparaison = pd.concat(
    [revenus, depenses],
    axis=1
)
comparaison.columns = [
    "revenus",
    "depenses"
]
print(comparaison)

         revenus      depenses
mois
1.0   600359.392  7.706013e+05
2.0   359794.967  1.242994e+06
3.0   370840.777  7.105000e+05

In [63]:
# Profit
comparaison["profit"] = (
    comparaison["revenus"]
    - comparaison["depenses"]
)
print(comparaison)

         revenus      depenses        profit
mois
1.0   600359.392  7.706013e+05 -170241.91296
2.0   359794.967  1.242994e+06 -883199.44396
3.0   370840.777  7.105000e+05 -339659.21896

## Analyse rentabilité client

In [66]:
# Revenu par client
revenus_clients = (
    df_ventes
    .groupby("client")["montant_ttc"]
    .sum()
)

In [67]:
# Nombre commande/client
freq_clients = (
    df_ventes
    .groupby("client")["vente_id"]
    .count()
)

In [68]:
# fusion
analyse_clients = pd.concat(
    [revenus_clients, freq_clients],
    axis=1
)
analyse_clients.columns = [
    "revenu_total",
    "nombre_commandes"
]
print(analyse_clients)

                          revenu_total  nombre_commandes
client
centre mdical la colombe    175823.375                 2
desmon esperith kibinda     689382.200                 2
gracia ikouadja              28536.000                 1
kwiza beach                  31567.950                 3
moussa yara                 150003.051                 3
prince koubaka                5992.560                 1
willis towers watson        285062.750                 4

***Clients réccurants: willis towers watson 4, moussa yara 3, kwiza beach 3***

In [70]:
# Revenu moyen client
analyse_clients["revenu_moyen"] = (
    analyse_clients["revenu_total"]
    / analyse_clients["nombre_commandes"]
)

In [71]:
analyse_clients["revenu_moyen"]

client
centre mdical la colombe     87911.6875
desmon esperith kibinda     344691.1000
gracia ikouadja              28536.0000
kwiza beach                  10522.6500
moussa yara                  50001.0170
prince koubaka                5992.5600
willis towers watson         71265.6875
Name: revenu_moyen, dtype: float64

## Analyse rentabilité services

In [72]:
# revenu par service
revenu_services = (
    df_ventes
    .groupby("service")["montant_ttc"]
    .sum()
)

In [73]:
# Fréquance service
freq_services = (
    df_ventes
    .groupby("service")["vente_id"]
    .count()
)

In [74]:
# Fusion
analyse_services = pd.concat(
    [revenu_services, freq_services],
    axis=1
)
analyse_services.columns = [
    "revenu_total",
    "nombre_ventes"
]
print(analyse_services)

               revenu_total  nombre_ventes
service
communication    150003.051              3
importation      689382.200              2
imprimerie       526982.635             11

***Service le plus demandé : Imprimerie***\n
***Service le plus rentable : Importation***

In [75]:
# revenu moyen par service
analyse_services["revenu_moyen"] = (
    analyse_services["revenu_total"]
    / analyse_services["nombre_ventes"]
)
print(analyse_services["revenu_moyen"])

service
communication     50001.017000
importation      344691.100000
imprimerie        47907.512273
Name: revenu_moyen, dtype: float64

## Analyse financière mensuelle

In [77]:
# Revenu mensuel
revenus_mensuels = (
    df_ventes
    .groupby(["annee", "mois"])["montant_ttc"]
    .sum()
)

In [78]:
# Dépense mensuelle
depenses_mensuelles = (
    df_operations
    .groupby(["annee", "mois"])["montant_ttc"]
    .sum()
)

In [80]:
finance = pd.concat(
    [revenus_mensuels, depenses_mensuelles],
    axis=1
)
finance.columns = [
    "revenus",
    "depenses"
]
print(finance)

                revenus      depenses
annee  mois
2026.0 1.0   600359.392  7.706013e+05
       2.0   359794.967  1.242994e+06
       3.0   370840.777  7.105000e+05

In [81]:
# Profit
finance["profit"] = (
    finance["revenus"]
    - finance["depenses"]
)
finance["profit"]

annee   mois
2026.0  1.0    -170241.91296
        2.0    -883199.44396
        3.0    -339659.21896
Name: profit, dtype: float64

In [82]:
# Ration rentabilité 
finance["ratio_rentabilite"] = (
    finance["profit"]
    / finance["revenus"]
) * 100
print(finance["ratio_rentabilite"])

annee   mois
2026.0  1.0     -28.356667
        2.0    -245.472985
        3.0     -91.591659
Name: ratio_rentabilite, dtype: float64

***Profit négatif (danger), forte hausse dépense (anomalie)***

## Analyse des dépenses critiques

In [87]:
# Dépense par catégories
depenses_categories = (
    df_operations
    .groupby("categorie_depense")["montant_ttc"]
    .sum()
    .sort_values(ascending=False)
)
print(depenses_categories)

categorie_depense
logement         750000.00000
administratif    665301.30900
maintenance      636525.00000
divers           544375.00000
internet          44999.98788
electricite       42894.41500
prestations       40000.00000
Name: montant_ttc, dtype: float64

In [88]:
# Pourcentage dépenses
pourcentage_depenses = (
    depenses_categories
    / depenses_categories.sum()
) * 100
print(pourcentage_depenses)

categorie_depense
logement         27.532072
administratif    24.422832
maintenance      23.366470
divers           19.983696
internet          1.651924
electricite       1.574630
prestations       1.468377
Name: montant_ttc, dtype: float64

***27% des dépense proviennent du logement, 24% des dépenses proviennent de l'administratif***

## Analyse fournisseur dominant

In [91]:
# Dépense par fournisseur
depenses_fournisseurs = (
    df_operations
    .groupby("beneficiaire")["montant_ttc"]
    .sum()

    .sort_values(ascending=False)
)
print(depenses_fournisseurs.head(10))

beneficiaire
ockoumou bettina     750000.0
imbiella cety        375000.0
jessy bounda         364500.0
prince ngoma         312425.0
désir koussafoula     90000.0
ets yc                90000.0
ets bathily           79500.0
ags electro           75000.0
buroshop              72500.0
ecobank               55000.0
Name: montant_ttc, dtype: float64

***Forte dépense envers ockoumou bettina, suivi de imbiella cety***

## Analyse des tendances

In [95]:
evolution_revenus = (
    df_ventes
    .groupby("mois")["montant_ttc"]
    .sum()
)
print(evolution_revenus)

mois
1.0    600359.392
2.0    359794.967
3.0    370840.777
Name: montant_ttc, dtype: float64

***Janvier est le mois le plus rentable***

In [96]:
evolution_depenses = (
    df_operations
    .groupby("mois")["montant_ttc"]
    .sum()
)
print(evolution_depenses)

mois
1    7.706013e+05
2    1.242994e+06
3    7.105000e+05
Name: montant_ttc, dtype: float64

***Les dépenses explosent en février***